const sharedSocketConfig = {
  PLAYER_POSITIONS_BUFFER_LENGTH: 5,
  CLIENT_SERVER_UPDATE_INTERVAL: 200,
  CLIENT_UPDATE_TYPE: 'CLIENT_UPDATE_TYPE',
  CLIENT_UPDATE_POSITION: 'CLIENT_UPDATE_POSITION',
  SOCKET_PAYLOAD: 'SOCKET_PAYLOAD',
  EVENT_SERVER_INIT_CLIENT: 'EVENT_SERVER_INIT_CLIENT',
  EVENT_CLIENT_UPDATE: 'EVENT_CLIENT_UPDATE',
  STATE_PROPS_POSITIONS: 'STATE_PROPS_POSITIONS',
};

try {
  module.exports = sharedSocketConfig;
} catch (err) {}
