const sharedSocketConfig = {
  PLAYER_POSITIONS_BUFFER_LENGTH: 5,
  CLIENT_SERVER_UPDATE_INTERVAL: 200,
  PROPNAME_TYPE: 'PROPNAME_TYPE',
  PROPNAME_POSITION: 'PROPNAME_POSITION',
  PROPNAME_PAYLOAD: 'PROPNAME_PAYLOAD',
  PROPNAME_POSITION_BUFFER: 'PROPNAME_POSITION_BUFFER',
  PROPNAME_POSITION_BUFFER_OFFSET: 'PROPNAME_POSITION_BUFFER_OFFSET',
  PROPNAME_ID: 'PROPNAME_ID',
  EVENT_SERVER_INIT_CLIENT: 'EVENT_SERVER_INIT_CLIENT',
  EVENT_CLIENT_UPDATE: 'EVENT_CLIENT_UPDATE',
  EVENT_SERVER_UPDATE: 'EVENT_SERVER_UPDATE',
};

try {
  module.exports = sharedSocketConfig;
} catch (err) {}
